import "./globals.css";
import type { Metadata } from "next";
import SideBar from "@/components/SideBar";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <SideBar />
        <Toaster richColors={true} visibleToasts={9} />
        {children}
      </body>
    </html>
  );
}
